In [4]:
import requests
import pandas as pd
import json
ACCESS_TOKEN = ''
# 
r=requests.get("https://api-qa.belcorp.biz/countries/", 
headers={"x-access-token":
ACCESS_TOKEN
})

In [5]:
dc = json.loads(r.content)
df_countries = pd.DataFrame(dc)

In [6]:
df_countries

,id,country_code,name,currency_symbol,language_code,contact,closing_time,label_code,phone_code
0,1,AR,Argentina,None,,,None,,+54
1,2,BO,Bolivia,Bs,,,None,,+591
2,3,CL,Chile,$,,,None,,+56
3,4,CO,Colombia,$,,,None,,+57
4,5,CR,Costa Rica,¢,,,None,,+506
5,6,EC,Ecuador,$,,,None,,+593
6,7,SV,El Salvador,$,,,None,,+503
7,8,GT,Guatemala,Q.,,,None,,+502
8,9,MX,México,$,,,None,,+52
9,10,PA,Panamá,B/.,,,None,,+507
10,11,PE,Perú,S/,,,None,,+51
11,12,PR,Puerto Rico,$,,,None,,+1
12,13,DO,República Dominicana,RD$,,,None,,+1
13,15,BR,Brasil,None,,,None,,+55
14,16,US,Estados Unidos,$,,,None,,+1